import '@fontsource/silkscreen';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{"random play dance <3"}</title>
      </head>
      <body style={{fontFamily: "'Silkscreen', sans-serif"}}>{children}</body>
    </html>
  )
}
